name: Tagesschau
url: https://www.tagesschau.de
language: de
political_orientation: neutral
type: public_service
rescrape_interval: 1800
feed_url: https://www.tagesschau.de/xml/rss2
scrape_method: rss
topics:
  - politics
  - economy
  - international
  - national
  - sports
quality_metrics:
  fact_checking: high
  source_citation: high
  editorial_standards: high
coverage:
  levels: [country, international]
  regions:
    - level: country
      code: DE
      name: Germany
    - level: international
      code: INT
      name: International 