services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/**/test/**'

    App\Infrastructure\Persistence\Config\DatabaseConfig:
        arguments:
            $host: '%env(DB_HOST)%'
            $port: '%env(int:DB_PORT)%'
            $name: '%env(DB_NAME)%'
            $user: '%env(DB_USER)%'
            $password: '%env(DB_PASSWORD)%'

    App\Infrastructure\Config\FileConfigService:
        arguments:
            $configDir: '%kernel.project_dir%/config'

    App\Infrastructure\Persistence\Factory\DatabaseConnectionFactory: ~
    App\Infrastructure\Persistence\Repository\PostgresNewsSourceRepository: ~
    App\Business\ArticleDownload\Domain\Service\NewsSourceImportService: ~ 