services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Infrastructure\Config\FileConfigService:
        arguments:
            $configDir: '%kernel.project_dir%/tests/config'

    App\Business\ArticleDownload\test\behavioural\context\NewsSourceImportContext:
        public: true
        arguments:
            $importService: '@App\Business\ArticleDownload\Domain\Service\NewsSourceImportService'
            $repository: '@App\Business\ArticleDownload\Domain\Repository\NewsSourceRepository'
            $configService: '@App\Infrastructure\Config\FileConfigService'

    App\Business\ArticleDownload\Domain\Service\ArticleCollectionService:
        public: true

    App\Business\ArticleDownload\test\behavioural\context\TestDatabaseHelper:
        public: true
        arguments:
            $pdo: '@database_connection'

    App\Business\ArticleDownload\test\behavioural\context\TestFileHelper:
        public: true
        arguments:
            $configService: '@App\Infrastructure\Config\FileConfigService' 