name: Diarios de Madrid
url: https://www.diariosdemadrid.com
language: es
political_orientation: neutral
type: newspaper
feed_url: https://www.diariosdemadrid.com/rss/seccion/351/
scrape_method: rss
topics:
  - local_politics
  - local_economy
  - neighborhood_events
  - civic_news
quality_metrics:
  fact_checking: medium
  source_citation: medium
  editorial_standards: medium
coverage:
  levels: [city, state]
  regions:
    - level: state
      code: MAD
      name: Comunidad de Madrid
    - level: city
      code: MAD-CITY
      name: Madrid
metadata:
  founded: null
  update_frequency: high
  paywall: none
  owner: Crónica Madrid
  verified_date: "2025-04-11"
  verification_note: "RSS feed verified active for local news section 351" 